
IDENTITY = [
    "CERT", # FDIC Certificate #
    "REPDTE", # Report Date
    "RSSDID", # FEDERAL RESERVE ID NUMBER
    "NAME", # INSTITUTION NAME
    "CITY", # CITY
    "STALP", # FIPS STATE ALPHA CODE
    "ZIP", # ZIP CODE
    "BKCLASS", # INSTITUTION CLASS
    "REGAGNT", # PRIMARY REGULATING AGENCY
    "ESTYMD", # ESTABLISHED DATE
    "INSDATE", # Date of Deposit Insurance
    "ACTIVE", # ACTIVE INSTITUTION FLAG
    "ENDEFYMD", # INACTIVE DATE
    "NUMEMP", # NUMBER OF FULL TIME EMPLOYEES
    "OFFDOM", # Number of Domestic Offices
    "SPECGRPDESC",    # Asset Concentration Hierarchy Description
    "RSSDHCR", # RSSDID - High Regulatory Holder
    "NAMEHCR", # Bank Holding Company (Regulatory Top Holder)
    "MUTUAL", # Ownership Type
]

BALANCE_SHEET = [
    "ASSET", # Total assets
    "LIAB", # TOTAL LIABILITIES
    "EQ", # Equity capital
    "DEP", # Total deposits
    "DEPDOM", # Deposits held in domestic offices
    "LNLSNET", # LOANS AND LEASES-NET
    "LNLSGR", # LOANS AND LEASES-TOTAL
    "SC", # SECURITIES
    "CHBAL", # CASH & DUE FROM DEPOSITORY INST
    "FREPO", # FED FUNDS & REPOS SOLD
    "TRADE", # TRADING ACCOUNTS
    "BKPREM", # PREMISES AND FIXED ASSETS
    "ORE", # OTHER REAL ESTATE OWNED
    "INTAN", # INTANGIBLE ASSETS
    "AOA", # ALL OTH ASSETS
]

CAPITAL = [
    "RBC1AAJ", # LEVERAGE RATIO-PCA
    "RBCRWAJ", # TOTAL RBC RATIO-PCA
    "IDT1RWAJR", # TIER 1 RISK-BASED CAPITAL RATIO
    "RBCT1J", # TIER 1 RBC ADJUSTED LLR - PCA
    "RWAJT", # RWA-ADJUSTED-PCA-TOTAL RBC RAT
    "CBLRIND", # Community Bank Ratio
    "EQV", # BANK EQUITY CAPITAL/ASSETS
]

ASSET_QUALITY = [
    "NAASSET", # NONACCRUAL-TOTAL ASSETS
    "P3ASSET", # 30-89 DAYS P/D-TOTAL ASSETS
    "P9ASSET", # 90+ DAYS P/D-TOTAL ASSETS
    "NARECONS", # NONACCRUAL-RE*CONSTRUCTION
    "NARENRES", # NONACCRUAL-RE*NONFARM NONRES
    "NARERES", # NONACCRUAL-RE*1-4 FAMILY
    "NACI", # NONACCRUAL-C&I LOANS
    "NACON", # NONACCRUAL-CONSUMER LOANS
    "LNATRES", # ALLOW FOR LOANS LOSS ADJUSTED
    "ELNATR", # PROVISIONS FOR CREDIT LOSSES
    "NTLNLS", # TOTAL LN&LS NET CHARGE-OFFS
    "NTRE", # REAL ESTATE LOAN NET CHARGE-OFFS
    "NTCI", # COMMERCIAL LOAN NET CHARGE-OFFS
    "NTCON", # CONSUMER LOAN NET CHARGE-OFFS
    "NTCRCD", # CREDIT CARD LOAN NET CHARGE-OFFS
    "LNATRESR", # LOAN LOSS RESERVE/GROSS LN&LS
    "NCLNLSR", # N/C LNS & LS/GROSS LNS & LS
    "NPERFV", # NONPERF ASSETS/TOTAL ASSETS
]

LOAN_MIX = [
    "LNRE", # RE LOANS
    "LNRECONS", # RE CONSTRUCTION & LAND DEVELOP
    "LNRENRES", # RE NONFARM NONRESIDENTIAL PROP
    "LNRERES", # RE 1-4 FAMILY
    "LNREMULT", # RE MULTIFAMILY
    "LNCI", # C&I LOANS
    "LNCON", # CONSUMER LOANS
    "LNCRCD", # CONSUMER LOANS-CREDIT CARD PLAN
    "LNAUTO", # CONSUMER LOANS - AUTO
    "LNAG", # AGRICULTURAL LOANS
]

MANAGEMENT = [
    "EEFFR", # EFFICIENCY RATIO
    "ASTEMPM", # ASSETS PER EMPLOYEE IN MILLION
    "ERNASTR", # EARNING ASSETS / TOTAL ASSETS
]



EARNINGS = [
    "NETINC", # Net income
    "INTINC", # TOTAL INTEREST INCOME
    "EINTEXP", # TOTAL INTEREST EXPENSE
    "NIM", # NET INTEREST INCOME
    "NONII", # TOTAL NONINTEREST INCOME
    "NONIX", # TOTAL NONINTEREST EXPENSE
    "ITAX", # APPLICABLE INCOME TAXES
    "PTAXNETINC" # PRE-TAX NET INCOME OPERATING INCOME
    "IGLSEC", # SECURITIES GAINS AND LOSSES
    "EQCDIV", # CASH DIVIDENDS ON COMM & PREF
    "ROA", # Return on assets (ROA)
    "ROE", # Return on Equity (ROE)
    "ROAPTX", # Pretax return on assets
    "NIMY", # NET INTEREST MARGIN
    "INTINCY", # INTEREST INCOME TO EARNING ASSETS RATIO
    "INTEXPY", # INTEREST EXPENSE TO EARNING ASSETS RATIO
    "NONIIAY", # NONINTEREST INC/AVERAGE ASSETS
    "NONIXAY", # NONINTEREST EXP/AVERAGE ASSETS
    "ELNATRY", # CREDIT LOSS PROV/AVE ASSETS
]

LIQUIDITY = [
    "DEPINS", # ESTIMATED INSURED DEPOSITS
    "DEPUNINS", # ESTIMATED UNINSURED DEPOSITS IN DOMESTIC OFFICES AND IN INSU
    "COREDEP", # CORE DEPOSITS
    "BRO", # BROKERED DEP
    "BROINS", # BROKERED DEP-INSURED
    "DEPNIDOM", # NONINTEREST-BEARING DEP-DOM
    "DEPIDOM", # INTEREST-BEARING DEP-DOM
    "NTRTIME", # TIME DEPOSITS-TOTAL
    "NTRTMLG", # TIME DEPOSITS OVER $100M
    "VOLIAB", # VOLATILE LIABILITIES
    "DEPLSNB", # DEP THRU LIST SVC NOT BROKERED
    "LNLSDEPR", # NET LOANS & LEASES/DEPOSITS
    "DEPDASTR", # TOT DOMESTIC DEPOSIT / ASSET
    "OTHBFHLB", # OTHER LIABILITIES-FHLB
    "EFHLBADV", # ADVANCES FROM FHLBANK INT EXP
    "OTBFH1L", # FHLB ADV MAT REP ONE YR OR LESS
]

SENSITIVITY = [
    "SCAA", # TOTAL AVAILABLE-FOR-SALE AT AMORTIZED COST SECURITIES ON A C
    "SCAF", # SECURITIES-AF
    "SCHA", # SECURITIES-HA
    "SCHF", # TOTAL HELD-TO-MATURITY AT FAIR VALUE SECURITIES ON A CONSOLI
    "IGLSCA", # AVAILABLE-FOR-SALE SECS G/L
    "IGLSCH", # HELD-TO-MATURITY SECS G/L
    "SCMUNI", # MUNICIPAL SECURITIES
    "SCEQ", # EQUITY SECURITIES
    "SC1LES", # Fixed and floating rate debt securities (included above) wit
]





DEFAULT_FIELDS = (
    IDENTITY
    + BALANCE_SHEET
    + CAPITAL
    + ASSET_QUALITY
    + LOAN_MIX
    + MANAGEMENT
    + EARNINGS
    + LIQUIDITY
    + SENSITIVITY
)

assert len(DEFAULT_FIELDS) == len(set(DEFAULT_FIELDS)), "duplicate field in DEFAULT_FIELDS"

DEFAULT_FIELDS_PARAM = ",".join(DEFAULT_FIELDS)



def resolve_fields_param(override: str | None = None) -> str:
    if not override or not override.strip():
        return DEFAULT_FIELDS_PARAM

    fields = [f.strip().upper() for f in override.split(",") if f.strip()]
    unknown = sorted(set(fields) - set(DEFAULT_FIELDS))
    if unknown:
        import warnings

        warnings.warn(
            f"FDIC_FIELDS_PARAM has {len(unknown)} fields not in DEFAULT_FIELDS: "
            f"{', '.join(unknown)}",
            stacklevel=2,
        )
    return ",".join(fields)